BASE: ['']
TOOLBOX_MODE: "only_test"

TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 30
  LR: 1e-3
  MODEL_FILE_NAME: PURE_PURE_UBFC_DeepPhys
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/Volumes/Intenso/PURE"
    CACHED_PATH: "./cache/pure"
    FILE_LIST_PATH: "./data/file_lists/pure"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 36
        W: 36

VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "/Volumes/Intenso/PURE"
    CACHED_PATH: "./cache/pure"
    FILE_LIST_PATH: "./data/file_lists/pure"
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 36
        W: 36

TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW
    DATA_PATH: "/Volumes/Intenso/UBFC-rPPG"
    CACHED_PATH: "./cache/ubfc_test_deepphys"
    FILE_LIST_PATH: "./data/file_lists/ubfc_test_deepphys"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized', 'Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 36
        W: 36

DEVICE: cpu
NUM_OF_GPU_TRAIN: 0

LOG:
  PATH: runs/exp

MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys

INFERENCE:
  BATCH_SIZE: 2
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: "runs/exp/PURE_SizeW36_SizeH36_ClipLength180_DataTypeDiffNormalized_Standardized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/PreTrainedModels/PURE_PURE_UBFC_DeepPhys_Epoch29.pth"